# Get editor completions based on the config schema
# https://starship.rs/config-schema.json
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """
[](#383e78)\
$python\
$username\
[](bg:#555fb5 fg:#383e78)\
$directory\
[](fg:#555fb5 bg:#f7768e)\
$git_branch\
$git_status\
[](fg:#f7768e bg:#e0af68)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#e0af68 bg:#9ece6a)\
$docker_context\
[](fg:#9ece6a bg:#383e78)\
$time\
[ ](fg:#383e78)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#383e78"
style_root = "bg:#383e78"
format = '[ ]($style)'

[directory]
style = "bg:#555fb5"
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#ffffff bg:#e0af68"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:#ffffff bg:#f7768e)'

[git_status]
format = '[$all_status$ahead_behind ](fg:#ffffff bg:#f7768e)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#3B4252"
format = '[(\$virtualenv )]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M"
style = "bg:#383e78"
format = '[ $time ]($style)'

