#!/bin/bash

wallpp ~/Pictures/wallpaper/boy-cat.webp

cp ~/.config/kitty/catppuccin ~/.config/kitty/kitty.conf
cp ~/.config/hypr/catppuccin_blue ~/.config/hypr/hyprland.conf
cp ~/dotfiles/config/starship/catppuccin ~/.config/starship.toml
cp ~/dotfiles/zshrc/starship ~/.zshrc
cp ~/dotfiles/config/fastfetch/catppuccin ~/.config/fastfetch/config.jsonc
