#!/bin/bash

wallpp ~/Pictures/wallpaper/boy-cat.webp

cp ~/.config/kitty/catppuccin ~/.config/kitty/kitty.conf
cp ~/.config/hypr/catppuccin_blue ~/.config/hypr/hyprland.conf
cp ~/dotfiles/config/fastfetch/catppuccin ~/.config/fastfetch/config.jsonc
cp ~/dotfiles/zshrc/p10k ~/.zshrc
