#!/bin/bash

wallpp ~/Pictures/wallpaper/town-in-space.webp

cp ~/.config/kitty/dracula ~/.config/kitty/kitty.conf
cp ~/.config/hypr/dracula ~/.config/hypr/hyprland.conf
cp ~/dotfiles/zshrc/p10k ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
