#!/bin/bash

wallpp ~/Pictures/wallpaper/everforest_steps.webp

cp ~/.config/kitty/everforest ~/.config/kitty/kitty.conf
cp ~/.config/hypr/everforest ~/.config/hypr/hyprland.conf
cp ~/dotfiles/config/starship/everforest ~/.config/starship.toml
cp ~/dotfiles/zshrc/starship ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
