#!/bin/bash

wallpp ~/Pictures/wallpaper/gruvy_street.png

cp ~/.config/kitty/gruvbox ~/.config/kitty/kitty.conf
cp ~/.config/hypr/gruvbox ~/.config/hypr/hyprland.conf
cp ~/dotfiles/config/starship/gruvbox_arch.toml ~/.config/starship.toml
cp ~/dotfiles/zshrc/starship ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
