#!/bin/bash

wallpp ~/Pictures/wallpaper/gruvy_street.png

cp ~/.config/kitty/gruvbox ~/.config/kitty/kitty.conf
cp ~/.config/hypr/gruvbox ~/.config/hypr/hyprland.conf
cp ~/dotfiles/zshrc/p10k ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
