#!/bin/bash

wallpp ~/Pictures/wallpaper/retro-space.webp

cp ~/.config/kitty/nord ~/.config/kitty/kitty.conf
cp ~/.config/hypr/nord ~/.config/hypr/hyprland.conf
cp ~/dotfiles/zshrc/p10k ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
