#!/bin/bash

wallpp ~/Pictures/wallpaper/retro-space.webp

cp ~/.config/kitty/nord ~/.config/kitty/kitty.conf
cp ~/.config/hypr/nord ~/.config/hypr/hyprland.conf
cp ~/dotfiles/config/starship/nord_star.toml ~/.config/starship.toml
cp ~/dotfiles/zshrc/starship ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
