#!/bin/bash

wallpp ~/Pictures/wallpaper/mountain.jpg

cp ~/.config/kitty/teal-purple ~/.config/kitty/kitty.conf
cp ~/.config/hypr/teal-purple ~/.config/hypr/hyprland.conf
cp ~/dotfiles/zshrc/p10k ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
