#!/bin/bash

wallpp ~/Pictures/wallpaper/arch-dark-dracula.webp

cp ~/.config/kitty/tokyo-night ~/.config/kitty/kitty.conf
cp ~/.config/hypr/tokyo-night ~/.config/hypr/hyprland.conf
cp ~/dotfiles/zshrc/p10k ~/.zshrc
cp ~/dotfiles/config/fastfetch/anime-jakool ~/.config/fastfetch/config.jsonc
