#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: wallpp /path/to/wallpaper"
    exit 1
fi

WALL="$1"

pkill swaybg
sleep 0.2

# apply to BOTH monitors
swaybg -o DP-1 -i "$WALL" -m fill &
swaybg -o HDMI-A-1 -i "$WALL" -m fill &
