#!/usr/bin/env bash

# -------------------------
# KILL OLD INSTANCES CLEANLY
# -------------------------
pkill swaybg 2>/dev/null
pkill waybar 2>/dev/null

sleep 0.5

# -------------------------
# WALLPAPER
# -------------------------
WALL="/home/anthony/Pictures/wallpaper/orange-desert.jpg"

swaybg -o DP-1 -i "$WALL" -m fill \
       -o HDMI-A-1 -i "$WALL" -m fill &

# -------------------------
# WAYBAR
# -------------------------
waybar &
